# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
page-title-suffix: – Pablo Rodríguez
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
twitter: https://twitter.com/parmandorc
linkedin: https://www.linkedin.com/in/parmandorc
github: https://github.com/parmandorc

collections:
  projects:
    output: true
    permalink: /project/:path/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project

# Build settings
markdown: kramdown
gems:
- jekyll-autoprefixer
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
autoprefixer:
  only_production: true
  browsers:
  - "> 1%"
  - last 2 versions
  - Firefox ESR
  - Safari >= 8
